# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 22:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name_plural': 'Social media links'},
        ),
        migrations.AddField(
            model_name='social',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 17, 22, 37, 15, 887850, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 17, 22, 37, 20, 664508, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 17, 22, 37, 26, 152961, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 17, 22, 37, 29, 825338, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
